# Enter directory on Enter
[[mgr.prepend_keymap]]
on   = ["<Enter>"]
run  = "enter"
desc = "Enter directory"

# Open files explicitly with `o` (optional)
[[mgr.prepend_keymap]]
on   = ["o"]
run  = "open --hovered"
desc = "Open file (use open rules)"

# “Open with…” chooser on `O` (optional)
[[mgr.prepend_keymap]]
on   = ["O"]
run  = "open --hovered --interactive"
desc = "Open with…"

# -------- Quick jumps (Windows) --------
# Interactive path prompt → g <Space>
[[mgr.prepend_keymap]]
on   = ["g", " "]
run  = "cd --interactive"
desc = "Jump to path (interactive)"

# Home / User profile → g u
[[mgr.prepend_keymap]]
on   = ["g", "u"]
run  = "cd ~"
desc = "Go to User Profile (~)"

# Documents → g o  (swap to OneDrive line if yours is redirected)
[[mgr.prepend_keymap]]
on   = ["g", "o"]
run  = "cd ~/Documents"
# run = "cd ~/OneDrive/Documents"
desc = "Go to Documents"

# Downloads → g d
[[mgr.prepend_keymap]]
on   = ["g", "d"]
run  = "cd ~/Downloads"
desc = "Go to Downloads"

# Roaming AppData → g a r
[[mgr.prepend_keymap]]
on   = ["g", "a", "r"]
run  = "cd ~/AppData/Roaming"
desc = "Go to AppData/Roaming"

# DIAGNOSTIC: quit on F12 so we know this keymap loaded
[[mgr.prepend_keymap]]
on   = ["<F12>"]
run  = "quit"
desc = "TEST: Quit (F12)"
